# Generated by Django 4.1.7 on 2023-04-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('item_type', models.CharField(choices=[('product', 'Producto'), ('concept', 'Concepto'), ('repair', 'Reparación'), ('maintenace', 'Mtto'), ('install', 'Instal/Mont'), ('unmounting', 'Desmontaje')], max_length=11)),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['name'],
            },
        ),
    ]
