# Generated by Django 4.1.7 on 2023-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='measurement',
            field=models.CharField(blank=True, choices=[('u', 'Uno'), ('m', 'Metros'), ('kg', 'Kilogramos'), ('lts', 'Litros')], max_length=3, null=True, verbose_name='Unidad de medida'),
        ),
    ]
