# Generated by Django 4.1.7 on 2023-04-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
    ]
