# Generated by Django 4.2 on 2023-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('product', 'Producto'), ('concept', 'Concepto'), ('repair', 'Reparación'), ('maintenace', 'Mtto'), ('install', 'Instal/Mont'), ('unmounting', 'Desmontaje')], max_length=11, verbose_name='Tipo'),
        ),
    ]
