# Generated by Django 4.1.7 on 2023-04-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100, verbose_name='Síntoma')),
                ('flaw', models.CharField(max_length=100, verbose_name='Defecto')),
                ('repair_description', models.CharField(max_length=100, verbose_name='Reparación')),
                ('folio', models.CharField(max_length=10, verbose_name='No. folio')),
                ('check_diagnosis', models.BooleanField(verbose_name='Revisión/Diagnóstico')),
                ('repair', models.BooleanField(verbose_name='Reparacón')),
                ('install', models.BooleanField(verbose_name='Instal./Mont./Desmont.')),
                ('maintenance', models.BooleanField(verbose_name='Mtto')),
                ('kit_brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('kit_model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('kit_serial', models.CharField(max_length=20, verbose_name='No. de serie o Inv.')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Descripción del trabajo realizado')),
                ('executor_signature_date', models.DateField(verbose_name='Fecha')),
                ('customer_signature_date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['executor_signature_date'],
            },
        ),
    ]
