# Generated by Django 4.1.7 on 2023-04-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_active'),
        ('customers', '0004_customer_is_active'),
        ('executors', '0001_initial'),
        ('kits', '0002_kit_is_active'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='executors.executor', verbose_name='Ejecutor'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='items.item', verbose_name='Artículo o Servicio'),
        ),
        migrations.AddField(
            model_name='order',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kits.kit', verbose_name='Equipo'),
        ),
    ]
