# Generated by Django 4.1.7 on 2023-04-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
        ('orders', '0002_order_customer_order_executor_order_items_order_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executors.executor', verbose_name='Ejecutor'),
        ),
    ]
