# Generated by Django 4.2 on 2023-04-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
        ('orders', '0003_order_is_active_alter_order_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='executors.executor', verbose_name='Ejecutor'),
        ),
    ]
