# Generated by Django 4.2 on 2023-04-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0004_alter_order_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
