# Generated by Django 4.2 on 2023-04-22 03:03

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    ItemTimes = apps.get_model('orders', 'ItemTimes')
    for order in Order.objects.all():
        for item in order.items.all():
            ItemTimes(
                item=item,
                order=order,
                times=1
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_itemtimes'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, migrations.RunPython.noop)
    ]
