# Generated by Django 4.2 on 2023-04-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0007_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.ItemTimes', to='items.item', verbose_name='Artículo o Servicio'),
        ),
    ]
