# Generated by Django 4.2 on 2023-05-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0009_alter_itemtimes_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtimes',
            options={'verbose_name': 'Cantidad de Artículo', 'verbose_name_plural': 'Cantidades de Artículo'},
        ),
        migrations.AlterField(
            model_name='itemtimes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Artículo'),
        ),
    ]
