# Generated by Django 4.2 on 2023-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0010_alter_itemtimes_options_alter_itemtimes_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(editable=False, through='orders.ItemTimes', to='items.item', verbose_name='Artículo o Servicio'),
        ),
    ]
