# Generated by Django 4.2 on 2023-05-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0011_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtimes',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Artículo'),
        ),
    ]
