# Generated by Django 4.2 on 2023-05-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_itemtimes_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtimes',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
