# Generated by Django 4.2 on 2023-05-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_type'),
        ('orders', '0013_alter_itemtimes_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, editable=False, through='orders.ItemTimes', to='items.item', verbose_name='Artículo o Servicio'),
        ),
    ]
