# Generated by Django 4.1.7 on 2023-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('es', 'ESTATAL'), ('pr', 'PARTICULAR')], max_length=2, verbose_name='Tipo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('province', models.CharField(max_length=20, verbose_name='Provincia')),
                ('township', models.CharField(max_length=50, verbose_name='Municipio')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('client_nit', models.CharField(max_length=100, verbose_name='NIT')),
                ('bank_account', models.CharField(max_length=50, verbose_name='Nro. de Cuenta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
