# Generated by Django 4.1.7 on 2023-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='client_nit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIT'),
        ),
    ]
