# Generated by Django 4.1.7 on 2023-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_client_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_header',
            field=models.CharField(default='', max_length=150, verbose_name='Titular de la Cuenta'),
            preserve_default=False,
        ),
    ]
