# Generated by Django 4.1.7 on 2023-04-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('license_number', models.CharField(max_length=10, verbose_name='Licencia')),
                ('personal_id', models.CharField(max_length=11, verbose_name='No. CI')),
            ],
            options={
                'verbose_name': 'Ejecutor',
                'verbose_name_plural': 'Ejecutores',
                'ordering': ['full_name'],
            },
        ),
    ]
