# Generated by Django 4.2 on 2023-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
