# Generated by Django 4.1.7 on 2023-04-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0002_kit_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['name'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
